### ISSUE TITLE
Add errors to the provisioning file for fitting 

### ISSUE THREAD

**Issue by franpoz** [franpoz/SHERLOCK#48]
The current version of the file that one needs for the fitting looks like: 

```
# This example YAML file illustrates the provisioning of planet and star parameters. The star mass here is important
# because the semi-major axis is not being provided and thus, it'd need to be calculated from the period and the M_star.
settings:
  cpus: 7
planet:
  id: 231663901
  period: 1.4309133565904666
  t0: 1326.004206688168
  rp_rs: 0.10455530183261129
star:
  R_star: 1.02
  M_star: 1.05
```

But we need to also use the errors given by TLS, at least in the `period`. For the case of `T0`, TLS does not provide any error, but I would say that we can use a reasonable value of +-0.01 days
